### PR TITLE
Update to ES6

### LINKED ISSUE #11: update to es6

### PR DESCRIPTION
**Pull request by madtaras**
Fixes #11 
Migrate project to ES6
Update server side and unit test
Add babel for client
Replace jshint with eslint and create a local config for it

### CODE REVIEW

**Comment by madtaras** [comment]
@mjhea0 ES6 requires node.js >= 6.0.0

**Comment by mjhea0** [comment]
@madtaras go ahead an bump it to the latest version of Node. Thanks!

**Comment by madtaras** [comment]
@mjhea0 I changed node.js version to 6 in .travis.yml
Please review and merge

**Comment by mjhea0** [comment]
👍

**Pull request merged**
